CREATE TABLE "accounts" (
  id SERIAL PRIMARY KEY,
  name VARCHAR(20) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'USER',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);